import type { Metadata } from "next";
import { poppins, montserratAlternates, circularStd } from "@/lib/fonts";
import "./globals.css";
import { Header } from "@/components/header";
import { SideMenu } from "@/components/side-menu";
import { Footer } from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${montserratAlternates.variable} ${circularStd.variable} antialiased`}
      >
        <div className="flex min-h-screen">
          <SideMenu />
          <div className="flex-1">
            <Header />
            <main className="p-6">{children}</main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
