import type { Metadata } from "next";
import { poppins, montserratAlternates, circularStd } from "@/lib/fonts";
import "./globals.css";
import { Header } from "@/components/header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${montserratAlternates.variable} ${circularStd.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
