import type { Metadata } from "next";
import { Poppins, Montserrat_Alternates } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ['400', '500', '600', '700'],
  subsets: ["latin"],
});

const montserratAlternates = Montserrat_Alternates({
  variable: "--font-montserrat-alternates",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
});

const circularStd = localFont({
  src: [
    {
      path: "../public/fonts/CircularStd-Book.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/CircularStd-Book.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/CircularStd-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/CircularStd-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-circular-std",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${montserratAlternates.variable} ${circularStd.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

